config/routes.rb
Rails.application.routes.draw do
  resources :domains

  root 'domains#index'

end

app/models/domain.rb
class Domain < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name, :expiration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :expiration %><br>
    <%= f.date_select :expiration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Domains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Expiration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= domain.expiration %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @domain.expiration %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domains</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>